# Generated by Django 6.0.5 on 2026-06-02 11:25

import django.db.models.deletion
import vault.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'verbose_name': 'Interpret', 'verbose_name_plural': 'Interpreti'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-release_date'], 'verbose_name': 'Release', 'verbose_name_plural': 'Releasy'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['track_number'], 'verbose_name': 'Skladba', 'verbose_name_plural': 'Skladby'},
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(default='CZ', max_length=50, verbose_name='Země původu'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.CharField(blank=True, help_text='Zadej žánry oddělené čárkou (např. Underground Rap, Rave, Hardcore)', max_length=200, verbose_name='Žánry'),
        ),
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('ALBUM', 'Album'), ('EP', 'EP'), ('SINGLE', 'Single')], default='ALBUM', max_length=10, verbose_name='Typ releasu'),
        ),
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Číslo stopy na albu'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografie / Info'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, validators=[vault.models.validate_not_empty], verbose_name='Jméno interpreta'),
        ),
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='vault.artist', verbose_name='Interpret'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(validators=[vault.models.validate_release_date], verbose_name='Datum vydání'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=200, validators=[vault.models.validate_not_empty], verbose_name='Název alba'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(help_text='Formát: MM:SS (např. 00:03:45)', verbose_name='Délka skladby'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='vault.release', verbose_name='Release / Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, validators=[vault.models.validate_not_empty], verbose_name='Název skladby'),
        ),
    ]
