# Generated by Django 6.0.6 on 2026-06-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_artist_options_alter_release_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, help_text='Odkaz na profilový obrázek interpreta', max_length=500, null=True, verbose_name='URL obrázku interpreta'),
        ),
        migrations.AddField(
            model_name='release',
            name='image_url',
            field=models.URLField(blank=True, help_text='Odkaz na cover art (obálku) alba', max_length=500, null=True, verbose_name='URL obrázku alba'),
        ),
    ]
